### ISSUE TITLE
Get python transmitting and receiving

### ISSUE THREAD

**Issue by cujomalainey** [cujomalainey/Mass-Tach-Server#1]
We need the radio working in python, you can use your computer to control this. Just get python reading and writing to the trinket. @dktrotti will create a new branch in the sensors submodule that has a build for the trinket that simply replies back with what is received and flash the red LED when it receives something.

**Comment by cujomalainey** [comment]
Here is a command for sending a message to the trinket with the serial number 0x0013A20040E8331B

make sure you convert all your data to bytes otherwise you will get errors.

xbee.send("tx", dest_addr_long=struct.pack('>Q', 0x0013A20040E8331B), dest_addr=b"\xFF\xFE", data=b"\x54")

**Comment by dktrotti** [comment]
Added RadioSample branch to Mass-Tach-Sensors which contains a sketch that allows for simple radio testing.

**Comment by cujomalainey** [comment]
use this commit cujomalainey/Mass-Tach-Sensors@7bee1a23adfbd79b3a0d2a0fa2286e53239ff469

**Comment by cujomalainey** [comment]
Oh and kdan we are using the default Xbee module in python 3. Just do pip3 install xbee.

**Comment by cujomalainey** [comment]
done, not moving to jira
